# Generated by Django 4.1 on 2022-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
