# Generated by Django 4.1 on 2022-08-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='receipt_type',
            field=models.CharField(choices=[('Revenue Receipt', 'Revenue Receipt'), ('Capital Receipt', 'Capital Receipt')], default='Revenue Receipt', max_length=24),
        ),
    ]
