# Generated by Django 4.1 on 2022-08-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_reward_receipt_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='receipt_type',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('Revenue Receipt', 'Revenue Receipt'), ('Capital Receipt', 'Capital Receipt')], default='Revenue Receipt', max_length=24),
        ),
    ]
