# Generated by Django 4.1 on 2022-08-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_reward_receipt_type_receipt_receipt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_term',
            field=models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term')], max_length=12, null=True),
        ),
    ]
