# Generated by Django 4.1.1 on 2022-09-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employed',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
