# Generated by Django 4.1 on 2022-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_card_card_type_alter_currency_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10, null=True),
        ),
    ]
