# Generated by Django 4.1 on 2022-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_card_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomlete'), ('Pending', 'Pending')], max_length=18, null=True),
        ),
    ]
