# Generated by Django 4.1.1 on 2022-10-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='signature',
        ),
    ]
