# Generated by Django 4.1 on 2022-08-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_currency_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='country',
            new_name='country_of_origin',
        ),
    ]
